id: P003097
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1EE74
  title: གསེར་འོད་དམ་པ་མདོ་སྡེའི་དབང་པོའི་རྒྱལ་པོ། ༼སོག་ཡིག༽
  author: ''
  volumes:
    20488146e09b49cc8e21920299776fa8:
      image_group_id: I1KG17012
      title: ''
      volume_number: 1
      total_pages: 453
      base_file: v001.txt
